# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [60]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [61]:
baby_names = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')

### Step 4. See the first 10 entries

In [62]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [63]:
baby_names.drop(['Unnamed: 0', 'Id'], axis=1, inplace=True)

### Step 6. Is there more male or female names in the dataset?

In [64]:
baby_names['Gender'].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 7. Group the dataset by name and assign to names

In [65]:
names = baby_names.groupby('Name').sum(numeric_only=True).drop('Year', axis=1)

### Step 8. How many different names exist in the dataset?

In [66]:
names.shape[0]

17632

### Step 9. What is the name with most occurrences?

In [67]:
names.Count.idxmax()

'Jacob'

### Step 10. How many different names have the least occurrences?

In [68]:
names[names.Count == names.Count.min()].shape[0]

2578

### Step 11. What is the median name occurrence?

In [69]:
names[names.Count == names.Count.median()]

         Count
Name
Aishani     49
Alara       49
Alysse      49
Ameir       49
Anely       49
...        ...
Sriram      49
Trinton     49
Vita        49
Yoni        49
Zuleima     49

[66 rows x 1 columns]

### Step 12. What is the standard deviation of names?

In [70]:
names.Count.std()

11006.069467891111

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [71]:
names.describe()

               Count
count   17632.000000
mean     2008.932169
std     11006.069468
min         5.000000
25%        11.000000
50%        49.000000
75%       337.000000
max    242874.000000