### Step 1. Import the necessary libraries

In [40]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [41]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

In [42]:
chipo = pd.read_csv(url,sep = '\t')

In [43]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 4. How many products cost more than $10.00?

In [44]:
chipo['item_price']=chipo['item_price'].str.replace('$','').astype(float)

In [45]:
chipo_filtered = chipo.drop_duplicates(['item_name', 'choice_description', 'item_price'])

In [46]:
chipo_one_product = chipo_filtered[chipo_filtered.quantity==1]

In [47]:
products_above_10 = chipo_one_product[chipo_one_product.item_price>10]

In [48]:
print(products_above_10['item_name'].nunique())

25

### Step 5. What is the price of each item?
###### print a data frame with only two columns item_name and item_price

In [49]:
sub_chipo = chipo[['item_name', 'item_price']]

In [50]:
item_prices = sub_chipo.drop_duplicates()

In [51]:
item_prices = item_prices.sort_values(by='item_price', ascending=False)

In [52]:
print(item_prices)

                         item_name  item_price
3598  Chips and Fresh Tomato Salsa       44.25
3480                 Carnitas Bowl       35.25
1254               Chicken Burrito       35.00
3601                Veggie Burrito       33.75
409                   Chicken Bowl       32.94
...                            ...         ...
6                    Side of Chips        1.69
329                  Bottled Water        1.50
263              Canned Soft Drink        1.25
28                     Canned Soda        1.09
34                   Bottled Water        1.09

[209 rows x 2 columns]

### Step 6. Sort by the name of the item

In [53]:
chipo.sort_values(by='item_name',ascending=True)

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [54]:
sorted_item_price=chipo.sort_values(by='item_price',ascending=False)

In [55]:
print(sorted_item_price['quantity'].iloc[0])

15

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [56]:
chipo_salad=chipo[chipo.item_name=='Veggie Salad Bowl']

In [57]:
len(chipo_salad)

18

###Step 9.Frequently Ordered item

In [58]:
chipo['item_name'].value_counts().idxmax()

'Chicken Bowl'

### Step 10. How many times did someone order more than one Canned Soda?

In [59]:
len(chipo[(chipo.item_name=='Canned Soda') & (chipo.quantity>1)])

20