# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [20]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [21]:
cars1 = pd.read_csv('/content/cars1[1].csv')
cars2 = pd.read_csv('/content/cars2[1].csv')

In [22]:
print(cars1.head())
print(cars2.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70
1  15.0          8           350        165    3693          11.5     70
2  18.0          8           318        150    3436          11.0     70
3  16.0          8           304        150    3433          12.0     70
4  17.0          8           302        140    3449          10.5     70

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN
1       1          buick skylark 320         NaN          NaN          NaN
2       1         plymouth satellite         NaN          NaN          NaN
3       1              amc rebel sst         NaN          NaN          NaN
4       1                ford torino         NaN          NaN          NaN

   Unnamed: 12  Unnamed: 13
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN
    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  33.0          4            91         53    1795          17.4     76
1  20.0          6           225        100    3651          17.7     76
2  18.0          6           250         78    3574          21.0     76
3  18.5          6           250        110    3645          16.2     76
4  17.5          6           258         95    3193          17.8     76

   origin                 car
0       3         honda civic
1       1      dodge aspen se
2       1   ford granada ghia
3       1  pontiac ventura sj
4       1       amc pacer d/l

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [23]:
cars1 = cars1.loc[:,'mpg':'car']

### Step 5. What is the number of observations in each dataset?

In [24]:
print(cars1.shape)
print(cars2.shape)

(198, 9)
(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [25]:
cars = pd.concat([cars1,cars2])
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [26]:
np_owners = np.random.randint(15000,73000,cars.shape[0])
np_owners

array([19923, 60797, 24989, 64724, 15936, 17513, 19872, 63169, 50353,
       50215, 69482, 28462, 41005, 45570, 42257, 52693, 40293, 26660,
       56837, 34494, 58908, 67875, 57854, 42534, 44909, 69802, 70199,
       34014, 15209, 22413, 59641, 60051, 37484, 16233, 35988, 41338,
       61933, 15395, 31209, 72235, 71640, 70447, 52068, 43965, 47661,
       48399, 40984, 59813, 32855, 44594, 44405, 20196, 54485, 37894,
       51423, 54489, 70527, 63469, 41675, 68291, 58784, 32223, 29179,
       41894, 27903, 49862, 44437, 48451, 66473, 41954, 47498, 29498,
       28330, 23853, 21813, 41996, 50181, 23856, 17358, 55225, 70526,
       36682, 60934, 43364, 72273, 66787, 23291, 18586, 31516, 57328,
       60280, 52766, 23914, 59973, 57670, 47078, 61593, 64651, 23908,
       65631, 48095, 59353, 64929, 32177, 15209, 36834, 24889, 27859,
       35637, 53360, 70352, 71804, 49329, 63201, 19868, 64421, 51989,
       57794, 38512, 45870, 25342, 28182, 67436, 20035, 72404, 63635,
       35341, 29985, 33383, 51540, 41723, 52683, 18481, 37934, 38387,
       17243, 70664, 16433, 45337, 45518, 66812, 38175, 44007, 27616,
       26726, 53075, 39937, 24005, 23085, 58283, 60005, 26768, 57384,
       33505, 21317, 40545, 55644, 31269, 47300, 44298, 21158, 56089,
       40057, 33265, 69477, 32726, 70342, 38665, 34699, 21065, 16984,
       61796, 17386, 65121, 59048, 55527, 58635, 17373, 53477, 23219,
       59932, 53012, 54869, 29881, 67856, 64982, 57253, 52321, 31810,
       72887, 50147, 72099, 27695, 41316, 68638, 43006, 36231, 34082,
       42842, 66102, 15183, 60387, 50769, 44430, 71649, 35093, 42041,
       48627, 36595, 65632, 43262, 17333, 33805, 35178, 71491, 48302,
       59171, 64393, 56830, 72981, 50192, 37207, 61801, 46015, 60621,
       59441, 16993, 29268, 47019, 71374, 26543, 45972, 33775, 72095,
       22195, 48458, 25089, 58720, 25654, 22183, 38384, 57171, 46020,
       52150, 25427, 23069, 21272, 28337, 27342, 38941, 32902, 15330,
       36206, 59708, 68694, 46049, 22635, 49733, 26409, 34058, 52894,
       29763, 51184, 30950, 56434, 55360, 50893, 36508, 67995, 68560,
       62416, 41335, 23140, 57919, 28193, 15155, 27958, 19599, 40612,
       20735, 72779, 54574, 43088, 43679, 52156, 20205, 28632, 55186,
       66572, 53878, 34089, 24245, 36498, 31458, 72895, 71566, 40157,
       35628, 23759, 27066, 42261, 18186, 37367, 34305, 25780, 38782,
       46950, 16085, 15278, 52852, 58724, 69270, 54775, 44353, 23516,
       19420, 61676, 66122, 70984, 42018, 52282, 58581, 65708, 15069,
       45352, 36791, 26632, 23337, 16922, 17617, 24996, 15588, 27661,
       43953, 66907, 55767, 62328, 39128, 36833, 18484, 38593, 52239,
       20512, 18289, 42796, 45804, 49597, 30692, 41741, 30406, 28566,
       60717, 47070, 56067, 38199, 30509, 63225, 28046, 60280, 64092,
       42588, 54293, 24493, 42848, 53876, 44514, 47817, 62124, 48911,
       19168, 25673, 33189, 32845, 42265, 34288, 16969, 42676, 64181,
       63175, 55567, 63424, 28306, 70779, 55453, 16712, 47684, 23286,
       20854, 33545, 40203, 56118, 30794, 61073, 44759, 27908, 20660,
       57502, 30163])

### Step 8. Add the column owners to cars

In [27]:
cars['owners'] = np_owners
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,19923
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,60797
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,24989
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,64724
4,17.0,8,302,140,3449,10.5,70,1,ford torino,15936

In [28]:
cars.shape

(398, 10)