# Investor - Flow of Funds - US

Check out [Investor Flow of Funds Exercises Video Tutorial](https://youtu.be/QG6WbOgC9QE) to watch a data scientist go through the exercises

### Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv).

### Step 3. Assign it to a variable called

In [2]:
url = 'https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv'
df = pd.read_csv(url)
df.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
1,2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2,2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
3,2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
4,2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 4.  What is the frequency of the dataset?

In [32]:
# weekly data

### Step 5. Set the column Date as the index.

In [3]:
df = df.set_index('Date')
df.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 6. What is the type of the index?

In [4]:
df.index
# it is a 'object' type

Index(['2022-07-06', '2022-07-13', '2022-07-20', '2022-07-27', '2022-08-03',
       '2022-08-10', '2022-08-17', '2022-08-24', '2022-08-31', '2022-09-07',
       ...
       '2025-09-03', '2025-09-10', '2025-09-17', '2025-09-24', '2025-10-01',
       '2025-10-08', '2026-06-03', '2026-06-10', '2026-06-17', '2026-06-24'],
      dtype='object', name='Date', length=114)

### Step 7. Set the index to a DatetimeIndex type

In [5]:
df.index = pd.to_datetime(df.index)
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex

### Step 8.  Change the frequency to monthly, sum the values and assign it to monthly.

In [6]:
monthly = df.resample('M').sum()
monthly

C:\Users\rajaa\AppData\Local\Temp\ipykernel_27268\3320231587.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly = df.resample('M').sum()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257,0.0,15635,0.0,11090,0.0,4545,0.0
2022-08-31,48663,0.0,32353,0.0,33705,0.0,-1352,0.0
2022-09-30,13775,0.0,10324,0.0,11629,0.0,-1305,0.0
2022-10-31,82879,0.0,55644,0.0,47435,0.0,8209,0.0
2022-11-30,82731,0.0,54314,0.0,37348,0.0,16967,0.0
2022-12-31,40451,0.0,29124,0.0,18273,0.0,10849,0.0
2023-01-31,34891,0.0,7853,0.0,-9945,0.0,17797,0.0
2023-02-28,13236,0.0,16460,0.0,6195,0.0,10264,0.0
2023-03-31,28861,0.0,3713,0.0,2500,0.0,1213,0.0
2023-04-30,39723,0.0,19058,0.0,14426,0.0,4632,0.0
2023-05-31,23789,0.0,6377,0.0,2020,0.0,4358,0.0
2023-06-30,62390,0.0,50665,0.0,39254,0.0,11408,0.0
2023-07-31,63164,0.0,46019,0.0,38479,0.0,7539,0.0
2023-08-31,18731,0.0,11968,0.0,10880,0.0,1089,0.0
2023-09-30,37875,0.0,29963,0.0,29830,0.0,133,0.0
2023-10-31,27572,0.0,13947,0.0,14375,0.0,-429,0.0
2023-11-30,114334,0.0,78791,0.0,73359,0.0,5433,0.0
2023-12-31,112558,0.0,99097,0.0,80368,0.0,18729,0.0
2024-01-31,58899,0.0,36802,0.0,30780,0.0,6022,0.0
2024-02-29,44315,0.0,36123,0.0,27302,0.0,8821,0.0
2024-03-31,105578,0.0,87666,0.0,76618,0.0,11047,0.0
2024-04-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-05-31,79344,0.0,51938,0.0,42353,0.0,9584,0.0
2024-06-30,79138,0.0,51872,0.0,39741,0.0,12131,0.0
2024-07-31,134078,0.0,98285,0.0,95686,0.0,2598,0.0
2024-08-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-09-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-10-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-12-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-02-28,0,0.0,0,0.0,0,0.0,0,0.0
2025-03-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-04-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-05-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-06-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-07-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-08-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-09-30,125005,0.0,72886,0.0,48603,0.0,24282,0.0
2025-10-31,79460,0.0,53892,0.0,42312,0.0,11580,0.0
2025-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-12-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-02-28,0,0.0,0,0.0,0,0.0,0,0.0
2026-03-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-04-30,0,0.0,0,0.0,0,0.0,0,0.0
2026-05-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-06-30,211092,0.0,163602,0.0,137081,0.0,26519,0.0

### Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.

In [7]:
monthly = monthly.dropna()
monthly

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257,0.0,15635,0.0,11090,0.0,4545,0.0
2022-08-31,48663,0.0,32353,0.0,33705,0.0,-1352,0.0
2022-09-30,13775,0.0,10324,0.0,11629,0.0,-1305,0.0
2022-10-31,82879,0.0,55644,0.0,47435,0.0,8209,0.0
2022-11-30,82731,0.0,54314,0.0,37348,0.0,16967,0.0
2022-12-31,40451,0.0,29124,0.0,18273,0.0,10849,0.0
2023-01-31,34891,0.0,7853,0.0,-9945,0.0,17797,0.0
2023-02-28,13236,0.0,16460,0.0,6195,0.0,10264,0.0
2023-03-31,28861,0.0,3713,0.0,2500,0.0,1213,0.0
2023-04-30,39723,0.0,19058,0.0,14426,0.0,4632,0.0
2023-05-31,23789,0.0,6377,0.0,2020,0.0,4358,0.0
2023-06-30,62390,0.0,50665,0.0,39254,0.0,11408,0.0
2023-07-31,63164,0.0,46019,0.0,38479,0.0,7539,0.0
2023-08-31,18731,0.0,11968,0.0,10880,0.0,1089,0.0
2023-09-30,37875,0.0,29963,0.0,29830,0.0,133,0.0
2023-10-31,27572,0.0,13947,0.0,14375,0.0,-429,0.0
2023-11-30,114334,0.0,78791,0.0,73359,0.0,5433,0.0
2023-12-31,112558,0.0,99097,0.0,80368,0.0,18729,0.0
2024-01-31,58899,0.0,36802,0.0,30780,0.0,6022,0.0
2024-02-29,44315,0.0,36123,0.0,27302,0.0,8821,0.0
2024-03-31,105578,0.0,87666,0.0,76618,0.0,11047,0.0
2024-04-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-05-31,79344,0.0,51938,0.0,42353,0.0,9584,0.0
2024-06-30,79138,0.0,51872,0.0,39741,0.0,12131,0.0
2024-07-31,134078,0.0,98285,0.0,95686,0.0,2598,0.0
2024-08-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-09-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-10-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-12-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-02-28,0,0.0,0,0.0,0,0.0,0,0.0
2025-03-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-04-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-05-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-06-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-07-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-08-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-09-30,125005,0.0,72886,0.0,48603,0.0,24282,0.0
2025-10-31,79460,0.0,53892,0.0,42312,0.0,11580,0.0
2025-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-12-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-02-28,0,0.0,0,0.0,0,0.0,0,0.0
2026-03-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-04-30,0,0.0,0,0.0,0,0.0,0,0.0
2026-05-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-06-30,211092,0.0,163602,0.0,137081,0.0,26519,0.0

### Step 10. Good, now we have the monthly data. Now change the frequency to year.

In [15]:
year = monthly.resample('YS-MAR').sum()
year

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-03-01,351883,0.0,221707,0.0,155730,0.0,65974,0.0
2023-03-01,632211,0.0,432523,0.0,363573,0.0,68948,0.0
2024-03-01,398138,0.0,289761,0.0,254398,0.0,35360,0.0
2025-03-01,204465,0.0,126778,0.0,90915,0.0,35862,0.0
2026-03-01,211092,0.0,163602,0.0,137081,0.0,26519,0.0

In [13]:
help(monthly.resample)

Help on method resample in module pandas.core.generic:

resample(rule, axis: 'Axis | lib.NoDefault' = <no_default>, closed: "Literal['right', 'left'] | None" = None, label: "Literal['right', 'left'] | None" = None, convention: "Literal['start', 'end', 's', 'e']" = 'start', kind: "Literal['timestamp', 'period'] | None | lib.NoDefault" = <no_default>, on: 'Level | None' = None, level: 'Level | None' = None, origin: 'str | TimestampConvertibleTypes' = 'start_day', offset: 'TimedeltaConvertibleTypes | None' = None, group_keys: 'bool_t' = False) -> 'Resampler' method of pandas.core.frame.DataFrame instance
    Resample time-series data.

    Convenience method for frequency conversion and resampling of time series.
    The object must have a datetime-like index (`DatetimeIndex`, `PeriodIndex`,
    or `TimedeltaIndex`), or the caller must pass the label of a datetime-like
    series/index to the ``on``/``level`` keyword parameter.

    Parameters
    ----------
    rule : DateOffset, Timedelta or str
        The offset string or object representing target conversion.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Which axis to use for up- or down-sampling. For `Series` this parameter
        is unused and defaults to 0. Must be
        `DatetimeIndex`, `TimedeltaIndex` or `PeriodIndex`.

        .. deprecated:: 2.0.0
            Use frame.T.resample(...) instead.
    closed : {'right', 'left'}, default None
        Which side of bin interval is closed. The default is 'left'
        for all frequency offsets except for 'ME', 'YE', 'QE', 'BME',
        'BA', 'BQE', and 'W' which all have a default of 'right'.
    label : {'right', 'left'}, default None
        Which bin edge label to label bucket with. The default is 'left'
        for all frequency offsets except for 'ME', 'YE', 'QE', 'BME',
        'BA', 'BQE', and 'W' which all have a default of 'right'.
    convention : {'start', 'end', 's', 'e'}, default 'start'
        For `PeriodIndex` only, controls whether to use the start or
        end of `rule`.

    kind : {'timestamp', 'period'}, optional, default None
        Pass 'timestamp' to convert the resulting index to a
        `DateTimeIndex` or 'period' to convert it to a `PeriodIndex`.
        By default the input representation is retained.

        .. deprecated:: 2.2.0
            Convert index to desired type explicitly instead.

    on : str, optional
        For a DataFrame, column to use instead of index for resampling.
        Column must be datetime-like.
    level : str or int, optional
        For a MultiIndex, level (name or number) to use for
        resampling. `level` must be datetime-like.
    origin : Timestamp or str, default 'start_day'
        The timestamp on which to adjust the grouping. The timezone of origin
        must match the timezone of the index.
        If string, must be one of the following:

        - 'epoch': `origin` is 1970-01-01
        - 'start': `origin` is the first value of the timeseries
        - 'start_day': `origin` is the first day at midnight of the timeseries

        - 'end': `origin` is the last value of the timeseries
        - 'end_day': `origin` is the ceiling midnight of the last day

        .. versionadded:: 1.3.0

        .. note::

            Only takes effect for Tick-frequencies (i.e. fixed frequencies like
            days, hours, and minutes, rather than months or quarters).
    offset : Timedelta or str, default is None
        An offset timedelta added to the origin.

    group_keys : bool, default False
        Whether to include the group keys in the result index when using
        ``.apply()`` on the resampled object.

        .. versionadded:: 1.5.0

            Not specifying ``group_keys`` will retain values-dependent behavior
            from pandas 1.4 and earlier (see :ref:`pandas 1.5.0 Release notes
            <whatsnew_150.enhancements.resample_group_keys>` for examples).

        .. versionchanged:: 2.0.0

            ``group_keys`` now defaults to ``False``.

    Returns
    -------
    pandas.api.typing.Resampler
        :class:`~pandas.core.Resampler` object.

    See Also
    --------
    Series.resample : Resample a Series.
    DataFrame.resample : Resample a DataFrame.
    groupby : Group Series/DataFrame by mapping, function, label, or list of labels.
    asfreq : Reindex a Series/DataFrame with the given frequency without grouping.

    Notes
    -----
    See the `user guide
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#resampling>`__
    for more.

    To learn more about the offset strings, please see `this link
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects>`__.

    Examples
    --------
    Start by creating a series with 9 one minute timestamps.

    >>> index = pd.date_range('1/1/2000', periods=9, freq='min')
    >>> series = pd.Series(range(9), index=index)
    >>> series
    2000-01-01 00:00:00    0
    2000-01-01 00:01:00    1
    2000-01-01 00:02:00    2
    2000-01-01 00:03:00    3
    2000-01-01 00:04:00    4
    2000-01-01 00:05:00    5
    2000-01-01 00:06:00    6
    2000-01-01 00:07:00    7
    2000-01-01 00:08:00    8
    Freq: min, dtype: int64

    Downsample the series into 3 minute bins and sum the values
    of the timestamps falling into a bin.

    >>> series.resample('3min').sum()
    2000-01-01 00:00:00     3
    2000-01-01 00:03:00    12
    2000-01-01 00:06:00    21
    Freq: 3min, dtype: int64

    Downsample the series into 3 minute bins as above, but label each
    bin using the right edge instead of the left. Please note that the
    value in the bucket used as the label is not included in the bucket,
    which it labels. For example, in the original series the
    bucket ``2000-01-01 00:03:00`` contains the value 3, but the summed
    value in the resampled bucket with the label ``2000-01-01 00:03:00``
    does not include 3 (if it did, the summed value would be 6, not 3).

    >>> series.resample('3min', label='right').sum()
    2000-01-01 00:03:00     3
    2000-01-01 00:06:00    12
    2000-01-01 00:09:00    21
    Freq: 3min, dtype: int64

    To include this value close the right side of the bin interval,
    as shown below.

    >>> series.resample('3min', label='right', closed='right').sum()
    2000-01-01 00:00:00     0
    2000-01-01 00:03:00     6
    2000-01-01 00:06:00    15
    2000-01-01 00:09:00    15
    Freq: 3min, dtype: int64

    Upsample the series into 30 second bins.

    >>> series.resample('30s').asfreq()[0:5]   # Select first 5 rows
    2000-01-01 00:00:00   0.0
    2000-01-01 00:00:30   NaN
    2000-01-01 00:01:00   1.0
    2000-01-01 00:01:30   NaN
    2000-01-01 00:02:00   2.0
    Freq: 30s, dtype: float64

    Upsample the series into 30 second bins and fill the ``NaN``
    values using the ``ffill`` method.

    >>> series.resample('30s').ffill()[0:5]
    2000-01-01 00:00:00    0
    2000-01-01 00:00:30    0
    2000-01-01 00:01:00    1
    2000-01-01 00:01:30    1
    2000-01-01 00:02:00    2
    Freq: 30s, dtype: int64

    Upsample the series into 30 second bins and fill the
    ``NaN`` values using the ``bfill`` method.

    >>> series.resample('30s').bfill()[0:5]
    2000-01-01 00:00:00    0
    2000-01-01 00:00:30    1
    2000-01-01 00:01:00    1
    2000-01-01 00:01:30    2
    2000-01-01 00:02:00    2
    Freq: 30s, dtype: int64

    Pass a custom function via ``apply``

    >>> def custom_resampler(arraylike):
    ...     return np.sum(arraylike) + 5
    ...
    >>> series.resample('3min').apply(custom_resampler)
    2000-01-01 00:00:00     8
    2000-01-01 00:03:00    17
    2000-01-01 00:06:00    26
    Freq: 3min, dtype: int64

    For a Series with a PeriodIndex, the keyword `convention` can be
    used to control whether to use the start or end of `rule`.

    Resample a year by quarter using 'start' `convention`. Values are
    assigned to the first quarter of the period.

    >>> s = pd.Series(
    ...     [1, 2], index=pd.period_range("2012-01-01", freq="Y", periods=2)
    ... )
    >>> s
    2012    1
    2013    2
    Freq: Y-DEC, dtype: int64
    >>> s.resample("Q", convention="start").asfreq()
    2012Q1    1.0
    2012Q2    NaN
    2012Q3    NaN
    2012Q4    NaN
    2013Q1    2.0
    2013Q2    NaN
    2013Q3    NaN
    2013Q4    NaN
    Freq: Q-DEC, dtype: float64

    Resample quarters by month using 'end' `convention`. Values are
    assigned to the last month of the period.

    >>> q = pd.Series(
    ...     [1, 2, 3, 4], index=pd.period_range("2018-01-01", freq="Q", periods=4)
    ... )
    >>> q
    2018Q1    1
    2018Q2    2
    2018Q3    3
    2018Q4    4
    Freq: Q-DEC, dtype: int64
    >>> q.resample("M", convention="end").asfreq()
    2018-03    1.0
    2018-04    NaN
    2018-05    NaN
    2018-06    2.0
    2018-07    NaN
    2018-08    NaN
    2018-09    3.0
    2018-10    NaN
    2018-11    NaN
    2018-12    4.0
    Freq: M, dtype: float64

    For DataFrame objects, the keyword `on` can be used to specify the
    column instead of the index for resampling.

    >>> d = {'price': [10, 11, 9, 13, 14, 18, 17, 19],
    ...      'volume': [50, 60, 40, 100, 50, 100, 40, 50]}
    >>> df = pd.DataFrame(d)
    >>> df['week_starting'] = pd.date_range('01/01/2018',
    ...                                     periods=8,
    ...                                     freq='W')
    >>> df
       price  volume week_starting
    0     10      50    2018-01-07
    1     11      60    2018-01-14
    2      9      40    2018-01-21
    3     13     100    2018-01-28
    4     14      50    2018-02-04
    5     18     100    2018-02-11
    6     17      40    2018-02-18
    7     19      50    2018-02-25
    >>> df.resample('ME', on='week_starting').mean()
                   price  volume
    week_starting
    2018-01-31     10.75    62.5
    2018-02-28     17.00    60.0

    For a DataFrame with MultiIndex, the keyword `level` can be used to
    specify on which level the resampling needs to take place.

    >>> days = pd.date_range('1/1/2000', periods=4, freq='D')
    >>> d2 = {'price': [10, 11, 9, 13, 14, 18, 17, 19],
    ...       'volume': [50, 60, 40, 100, 50, 100, 40, 50]}
    >>> df2 = pd.DataFrame(
    ...     d2,
    ...     index=pd.MultiIndex.from_product(
    ...         [days, ['morning', 'afternoon']]
    ...     )
    ... )
    >>> df2
                          price  volume
    2000-01-01 morning       10      50
               afternoon     11      60
    2000-01-02 morning        9      40
               afternoon     13     100
    2000-01-03 morning       14      50
               afternoon     18     100
    2000-01-04 morning       17      40
               afternoon     19      50
    >>> df2.resample('D', level=0).sum()
                price  volume
    2000-01-01     21     110
    2000-01-02     22     140
    2000-01-03     32     150
    2000-01-04     36      90

    If you want to adjust the start of the bins based on a fixed timestamp:

    >>> start, end = '2000-10-01 23:30:00', '2000-10-02 00:30:00'
    >>> rng = pd.date_range(start, end, freq='7min')
    >>> ts = pd.Series(np.arange(len(rng)) * 3, index=rng)
    >>> ts
    2000-10-01 23:30:00     0
    2000-10-01 23:37:00     3
    2000-10-01 23:44:00     6
    2000-10-01 23:51:00     9
    2000-10-01 23:58:00    12
    2000-10-02 00:05:00    15
    2000-10-02 00:12:00    18
    2000-10-02 00:19:00    21
    2000-10-02 00:26:00    24
    Freq: 7min, dtype: int64

    >>> ts.resample('17min').sum()
    2000-10-01 23:14:00     0
    2000-10-01 23:31:00     9
    2000-10-01 23:48:00    21
    2000-10-02 00:05:00    54
    2000-10-02 00:22:00    24
    Freq: 17min, dtype: int64

    >>> ts.resample('17min', origin='epoch').sum()
    2000-10-01 23:18:00     0
    2000-10-01 23:35:00    18
    2000-10-01 23:52:00    27
    2000-10-02 00:09:00    39
    2000-10-02 00:26:00    24
    Freq: 17min, dtype: int64

    >>> ts.resample('17min', origin='2000-01-01').sum()
    2000-10-01 23:24:00     3
    2000-10-01 23:41:00    15
    2000-10-01 23:58:00    45
    2000-10-02 00:15:00    45
    Freq: 17min, dtype: int64

    If you want to adjust the start of the bins with an `offset` Timedelta, the two
    following lines are equivalent:

    >>> ts.resample('17min', origin='start').sum()
    2000-10-01 23:30:00     9
    2000-10-01 23:47:00    21
    2000-10-02 00:04:00    54
    2000-10-02 00:21:00    24
    Freq: 17min, dtype: int64

    >>> ts.resample('17min', offset='23h30min').sum()
    2000-10-01 23:30:00     9
    2000-10-01 23:47:00    21
    2000-10-02 00:04:00    54
    2000-10-02 00:21:00    24
    Freq: 17min, dtype: int64

    If you want to take the largest Timestamp as the end of the bins:

    >>> ts.resample('17min', origin='end').sum()
    2000-10-01 23:35:00     0
    2000-10-01 23:52:00    18
    2000-10-02 00:09:00    27
    2000-10-02 00:26:00    63
    Freq: 17min, dtype: int64

    In contrast with the `start_day`, you can use `end_day` to take the ceiling
    midnight of the largest Timestamp as the end of the bins and drop the bins
    not containing data:

    >>> ts.resample('17min', origin='end_day').sum()
    2000-10-01 23:38:00     3
    2000-10-01 23:55:00    15
    2000-10-02 00:12:00    45
    2000-10-02 00:29:00    45
    Freq: 17min, dtype: int64

### BONUS: Create your own question and answer it.